modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/BloodyMods/ExNihiloCreatio/issues"
displayURL="https://github.com/BloodyMods/ExNihiloCreatio/"
logoFile="examplemod.png"
authors="BloodWorkXGaming, SirLyle"

[[mods]]
    modId="exnihilocreatio"
    version="${file.jarVersion}
    displayName="Ex Nihilo Creatio"
    description="Creation from nothingness"

[[dependencies.roomery]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.roomery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2,)"
    ordering="NONE"
    side="BOTH"